### ISSUE TITLE
Error initializing step [Tableau Data Extract Output]

### ISSUE THREAD

**Issue by chabad001** [cdeptula/tdeoutputplugin#12]
Hi,

I have installed ‘TDE-API-C-Java-64Bit’ API and ‘TDEOutputPlugin’ plugin and i was to see the ‘Tableau Data Extract Output’ in Output. I am trying to read a select * from a table which has 6 rows and pushing it to TDE output. When i process it I am getting the below error.

**Error initializing step [Tableau Data Extract Output]**
[Pentaho Error.docx](https://github.com/cdeptula/tdeoutputplugin/files/215440/Pentaho.Error.docx)

I am using Pentaho Version 6.0.1.0-386 and Tableau 9.2.4. Can you throw some light on this?

Thanks,
Chandra

**Comment by cdeptula** [comment]
I have tested with Pentaho 6.0.1 and Tableau 9.1 and above and everything seems to work.  Based on your error the problem is almost definitely related to not following the steps to install in the readme correctly (Copied here.)

1. Download the Tableau SDK for Java from http://onlinehelp.tableau.com/current/api/sdk/en-us/SDK/tableau_sdk_installing.htm#downloading
2. Follow the instructions for your environment to install the Tableau SDK: http://onlinehelp.tableau.com/current/api/sdk/en-us/help.htm#SDK/tableau_sdk_using_java_eclipse.htm%3FTocPath%3D_____5
3. Copy the jar files from sdk-install-dir/Java to ${PDI_HOME}/plugins/steps/TDEOutputPlugin/lib directory.

**Comment by llealgt** [comment]
I'm getting this error, i know  the installation is correct because it is working for other jobs in the same machine, is there any logs i can check?
