### ISSUE TITLE
Error initializing step

### ISSUE THREAD

**Issue by mporracindie** [cdeptula/tdeoutputplugin#16]
Im getting this error:

`java.lang.NoClassDefFoundError: com/tableausoftware/DataExtract/TableDefinition
`

Doing some research i noticed i get this exception when i start the tomcat i get this:

`Failed to register plugin null
org.pentaho.platform.api.engine.PlatformPluginRegistrationException: PluginManager.ERROR_0026 - Plugin at found at "TDEOutputPlugin" has an empty or missing name`

Any idea why? The instalation seems to be fine.

**Comment by mporracindie** [comment]
I have the .jar files inside the plugin folder instalation.

![mporracindie_ _root_ip-10-64-4-11__home_pentahodis_test_ _ssh_-t_batmanaws_ml_com_ssh_-i___pentahoadmin_pem_ec2-user_10_64_4_11_ _227x53_and_reg_history_eds_data_ _main_ _sudo_ _114x27](https://user-images.githubusercontent.com/42622776/48574610-63431000-e8ee-11e8-9de0-b81790181f1f.png)

**Comment by cdeptula** [comment]
If you are using Pentaho 8.1, make sure you are using the latest version of the plugin.  Version 2.0.1.  There was a bug when the plugin was used in Pentaho 8.1 that caused some class loader issues.  This is fixed in release 2.0.1 of this plugin.  Otherwise according to your comments it should work fine.

**Comment by mporracindie** [comment]
I was using an old version of the plugin. Works fine now.

Thanks!
